# =============================================
#   Cau hinh DrawClient
#   Doi IP khi chuyen sang mang LAN khac
#   KHONG can build lai sau khi sua file nay
# =============================================

[Server]
MasterServerIp=10.225.37.92
MasterServerPort=5274
