# =============================================
#   Cau hinh DrawClient
#   Doi IP khi chuyen sang mang LAN khac
#   KHONG can build lai sau khi sua file nay
# =============================================

[Server]
MasterServerIp=172.30.126.158
MasterServerPort=5274
