# =============================================
#   Cấu hình DrawClient
#   Đổi IP khi chuyển sang mạng LAN khác
#   KHÔNG cần build lại sau khi sửa file này
# =============================================

[Server]
MasterServerIp=127.0.0.1
MasterServerPort=5274
